/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpa.easoftware.tap.view;

import br.ufpa.easoftware.tap.dao.DAOCalendario;
import br.ufpa.easoftware.tap.dao.DAODisciplinas;
import br.ufpa.easoftware.tap.dao.DAOEventos;
import br.ufpa.easoftware.tap.dao.DAOProfessores;
import br.ufpa.easoftware.tap.model.Calendario;
import br.ufpa.easoftware.tap.model.Eventos;
import br.ufpa.easoftware.tap.view.aluno.MenuAluno;
import br.ufpa.easoftware.tap.view.calendario.MenuCalendario;
import br.ufpa.easoftware.tap.view.cronograma.MenuCronograma;
import br.ufpa.easoftware.tap.view.disciplina.MenuDisciplina;
import br.ufpa.easoftware.tap.view.evento.MenuEventos;
import br.ufpa.easoftware.tap.view.professor.MenuProfessor;
import br.ufpa.easoftware.tap.view.tipoeventos.MenuTipoEventos;
import java.awt.Container;
import java.awt.FlowLayout;
import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author UEPA_LAB6
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Menu() {
        initComponents();        
        
        DAOProfessores daoProfessores = new DAOProfessores();                
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(daoProfessores.listar());
        jComboBoxProf.setModel(defaultComboBoxModel);                
        txtIdProfessor.setText("" +  jComboBoxProf.getItemAt(jComboBoxProf.getSelectedIndex()).charAt(0));        
        txtIdProfessor.setVisible(false);
        
        DAODisciplinas daoDisciplinas = new DAODisciplinas();                
        DefaultComboBoxModel defaultComboBoxModelDisc = new DefaultComboBoxModel(daoDisciplinas.listar());
        jComboBoxDisc.setModel(defaultComboBoxModelDisc);                
        txtIdDisciplina.setText("" +  jComboBoxDisc.getItemAt(jComboBoxDisc.getSelectedIndex()).charAt(0));        
        txtIdDisciplina.setVisible(false);                
        
        DAOEventos daoEventos = new DAOEventos();                
        DefaultComboBoxModel defaultComboBoxModelEven = new DefaultComboBoxModel(daoEventos.listar());
        jComboBoxEvento.setModel(defaultComboBoxModelEven);                
        txtIdEvento.setText("" +  jComboBoxEvento.getItemAt(jComboBoxEvento.getSelectedIndex()).charAt(0));        
        txtIdEvento.setVisible(false);
        
        jCheckBoxTodosProf.setVisible(false);
        jCheckBoxTodosDisci.setVisible(false);
        jCheckBoxTodosEven.setVisible(false);
        jComboBoxProf.setVisible(false);
        jComboBoxDisc.setVisible(false);        
        jComboBoxEvento.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxTodosProf = new javax.swing.JCheckBox();
        jCheckBoxTodosDisci = new javax.swing.JCheckBox();
        jComboBoxProf = new javax.swing.JComboBox<>();
        jComboBoxDisc = new javax.swing.JComboBox<>();
        txtIdProfessor = new javax.swing.JTextField();
        txtIdDisciplina = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxEvento = new javax.swing.JComboBox<>();
        jCheckBoxTodosEven = new javax.swing.JCheckBox();
        txtIdEvento = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxTodosProf.setText("Todos Professores");
        jCheckBoxTodosProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTodosProfMouseClicked(evt);
            }
        });
        jCheckBoxTodosProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodosProfActionPerformed(evt);
            }
        });

        jCheckBoxTodosDisci.setText("Todas Disciplinas");
        jCheckBoxTodosDisci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTodosDisciMouseClicked(evt);
            }
        });

        jComboBoxProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDisc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIdProfessor.setEnabled(false);
        txtIdProfessor.setName("idTipoEvento"); // NOI18N

        txtIdDisciplina.setEnabled(false);
        txtIdDisciplina.setName("idTipoEvento"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBoxEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBoxTodosEven.setText("Todas Eventos");
        jCheckBoxTodosEven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTodosEvenMouseClicked(evt);
            }
        });
        jCheckBoxTodosEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodosEvenActionPerformed(evt);
            }
        });

        txtIdEvento.setEnabled(false);
        txtIdEvento.setName("idTipoEvento"); // NOI18N

        jMenu1.setText("Cadastros");

        jMenu3.setText("Alunos");

        jMenuItem1.setText("Gerenciar Alunos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenu1.add(jMenu3);

        jMenu4.setText("Cronograma");

        jMenuItem2.setText("Gerenciar Cronograma");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu1.add(jMenu4);

        jMenu5.setText("Disciplinas");

        jMenuItem3.setText("Gerenciar Disciplinas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenu1.add(jMenu5);

        jMenu6.setText("Eventos");

        jMenuItem4.setText("Gerenciar Eventos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenu1.add(jMenu6);

        jMenu7.setText("Professor");

        jMenuItem5.setText("Gerenciar Professor");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenu1.add(jMenu7);

        jMenu8.setText("Tipo de Eventos");

        jMenuItem6.setText("Gerenciar Tipo Eventos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenu1.add(jMenu8);

        jMenu9.setText("Calendário");

        jMenuItem7.setText("Gerenciar Calendário");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem7);

        jMenu1.add(jMenu9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Painel Cronológico de Eventos");

        jMenuItem8.setText("Gerar Painel");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTodosProf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBoxTodosDisci, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxProf, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE)
                            .addComponent(jComboBoxDisc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxTodosEven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(txtIdProfessor)))
                    .addComponent(jComboBoxEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTodosProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTodosDisci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTodosEven)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTodosProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTodosProfMouseClicked
        // TODO add your handling code here:
        if (jCheckBoxTodosProf.isSelected()) {
            jComboBoxProf.setEnabled(false);
        } else {
            jComboBoxProf.setEnabled(true);        
        } 
    }//GEN-LAST:event_jCheckBoxTodosProfMouseClicked

    private void jCheckBoxTodosDisciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTodosDisciMouseClicked
        // TODO add your handling code here:
        if (jCheckBoxTodosDisci.isSelected()) {
            jComboBoxDisc.setEnabled(false);
        } else {
            jComboBoxDisc.setEnabled(true);        
        } 
    }//GEN-LAST:event_jCheckBoxTodosDisciMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MenuAluno menuAluno = new MenuAluno();
        menuAluno.setTitle("Gerenciar Alunos");
        menuAluno.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MenuCronograma menuCronograma = new MenuCronograma();
        menuCronograma.setTitle("Gerenciar Cronograma");
        menuCronograma.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MenuDisciplina menuDisciplinas = new MenuDisciplina();
        menuDisciplinas.setTitle("Gerenciar Disciplinas");
        menuDisciplinas.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MenuEventos menuEventos = new MenuEventos();
        menuEventos.setTitle("Gerenciar Eventos");
        menuEventos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        MenuProfessor menuProfessor = new MenuProfessor();
        menuProfessor.setTitle("Gerenciar Professor");
        menuProfessor.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        MenuTipoEventos menuTipoEventos = new MenuTipoEventos();
        menuTipoEventos.setTitle("Gerenciar Tipo Eventos");
        menuTipoEventos.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:       
        MenuCalendario menuCalendario = new MenuCalendario();
        menuCalendario.setTitle("Gerenciar Calendário");
        menuCalendario.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jCheckBoxTodosProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodosProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTodosProfActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jCheckBoxTodosProf.setVisible(true);
        jCheckBoxTodosDisci.setVisible(true);
        jComboBoxProf.setVisible(true);
        jComboBoxDisc.setVisible(true);  
        jComboBoxEvento.setVisible(true);
        
        DAOCalendario daoCalendario = new DAOCalendario();
        List<Calendario> dados = dados = daoCalendario.recuperaTodosCalendario();
        for (Calendario dado : dados) {
            Container c = this.getContentPane();
            c.setLayout(new FlowLayout());        
            Cal cal = new Cal();
            switch (dado.getMes()) {
                case 1: 
                {   
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 2: 
                {                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 3: 
                {                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 4: 
                {                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 5: 
                {                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 6: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 7: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 8: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 9: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 10: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 11: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
                case 12: 
                {                                
                    cal.monthChoice.setSelectedIndex(dado.getMes()-1);
                    break;
                }
            }           
            DAOEventos daoEventos = new DAOEventos();
            List<Eventos> dadosEve = daoEventos.recuperaEventosPorId(dado.getEvento().getId());
            cal.texto.setText(dadosEve.get(0).getDescricao());
            cal.setDayActive(dado.getDia());
            c.add(cal);
        }                       
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jCheckBoxTodosEvenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTodosEvenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTodosEvenMouseClicked

    private void jCheckBoxTodosEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodosEvenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTodosEvenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxTodosDisci;
    private javax.swing.JCheckBox jCheckBoxTodosEven;
    private javax.swing.JCheckBox jCheckBoxTodosProf;
    private javax.swing.JComboBox<String> jComboBoxDisc;
    private javax.swing.JComboBox<String> jComboBoxEvento;
    private javax.swing.JComboBox<String> jComboBoxProf;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdDisciplina;
    private javax.swing.JTextField txtIdEvento;
    private javax.swing.JTextField txtIdProfessor;
    // End of variables declaration//GEN-END:variables
}
