-- MySQL Script generated by MySQL Workbench
-- 09/13/18 18:42:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema sispace
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sispace` ;

-- -----------------------------------------------------
-- Schema sispace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sispace` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `sispace` ;

-- -----------------------------------------------------
-- Table `cronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cronograma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cronograma` (
  `id_cronograma` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `ano_letivo` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cronograma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `professor` (
  `id_professor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disciplinas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `disciplinas` (
  `id_disciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `id_professor` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `carga_horaria` INT(11) NULL DEFAULT NULL,
  `ementa` VARCHAR(200) NULL DEFAULT NULL,
  `creditos` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eventos` (
  `id_eventos` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`id_eventos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `calendario` (
  `id_calendario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_disciplina` INT(11) NOT NULL,
  `id_cronograma` INT(11) NOT NULL,
  `id_evento` INT(11) NOT NULL,
  `dia` INT(11) NULL DEFAULT NULL,
  `mes` INT(11) NULL DEFAULT NULL,
  `ano` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`id_calendario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
